<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LT-jiangxm" name="com.llwallet.interfaces.test.api.test.personal.ModifyBaseUserInfoTest" tests="2" failures="1" timestamp="2 Nov 2017 13:27:27 GMT" time="0.358" errors="1">
  <testcase name="modifyBaseUserInfo1" time="0.277" classname="com.llwallet.interfaces.test.api.test.personal.ModifyBaseUserInfoTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.ModifyBaseUserInfoTest.modifyBaseUserInfo1(ModifyBaseUserInfoTest.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- modifyBaseUserInfo1 -->
  <testcase name="modifyBaseUserInfo" time="0.081" classname="com.llwallet.interfaces.test.api.test.personal.ModifyBaseUserInfoTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
]]>
    </failure>
  </testcase> <!-- modifyBaseUserInfo -->
</testsuite> <!-- com.llwallet.interfaces.test.api.test.personal.ModifyBaseUserInfoTest -->
