<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LT-jiangxm" name="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest" tests="34" failures="7" timestamp="7 Dec 2017 08:33:32 GMT" time="14.869" errors="0">
  <testcase name="threeFactorsSignApply" time="0.188" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="1.206" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.255" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.199" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.671" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.517" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.743" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:61)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="0.343" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.347" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.377" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.203" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.209" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="1.162" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:61)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="0.519" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:61)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="0.642" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="0.164" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="1.608" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="0.173" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.195" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.213" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.410" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.494" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:61)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="0.171" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.174" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.590" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest.threeFactorsSignApply(ThreeFactorsSignApplyTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- threeFactorsSignApply -->
  <testcase name="threeFactorsSignApply" time="0.425" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.606" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.161" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.475" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.567" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.190" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.162" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.342" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
  <testcase name="threeFactorsSignApply" time="0.168" classname="com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest"/>
</testsuite> <!-- com.llwallet.interfaces.test.api.test.other.ThreeFactorsSignApplyTest -->
